resource:
  following_list:
    page_limit: 20

storage:
  bucket_name: devstorage
  bucket_id: 00262c752b929930000000001
  endpoint: https://s3.us-west-002.backblazeb2.com 
  region: 'us-west-002'
  app_key: K002TUDmzC5T4N9Ua/JCxma2FlT/RZM